version: "3.9"
services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    hostname: vault
    mem_limit: 512m
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.hcl
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8200
    ports:
      - 8200:8200
    volumes:
      - $PWD/vault.hcl:/vault/config/vault.hcl:rw
    environment:
      VAULT_ADDR: ${VAULT_ADDR:-http://0.0.0.0:8200}
      VAULT_DEV_LISTEN_ADDRESS: ${VAULT_DEV_LISTEN_ADDRESS:-0.0.0.0:8200}
      VAULT_SEAL_TYPE: ${VAULT_SEAL_TYPE:-awskms}
      VAULT_AWSKMS_SEAL_KEY_ID: ${VAULT_AWSKMS_SEAL_KEY_ID:-00000000-0000-0000-0000-000000000000}
      AWS_REGION: ${AWS_REGION:-eu-west-2}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-dummy}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-dummy}
      AWS_KMS_ENDPOINT: ${AWS_KMS_ENDPOINT:-http://local-kms:8080}
    restart: on-failure:5
  local-kms:
    image: nsmithuk/local-kms:latest
    container_name: local-kms
    hostname: local-kms
    ports:
      - 8080:8080
    volumes:
      - $PWD/seed.yaml:/init/seed.yaml:rw
