version: "3.9"
services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    hostname: vault
    mem_limit: 512m
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.hcl
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8200
    ports:
      - 8200:8200
    volumes:
      - $PWD/vault.hcl:/vault/config/vault.hcl:rw
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    restart: on-failure:5
  local-kms:
    image: nsmithuk/local-kms:latest
    container_name: local-kms
    hostname: local-kms
    ports:
      - 8080:8080
    volumes:
      - $PWD/seed.yaml:/init/seed.yaml:rw
